[package]
name = "bevy_text_wrap_fix"
version = "0.1.0"
authors = ["Niklas Eicker <git@nikl.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = { version = "0.7" }
bevy = { path = "../bevy" }
